<a href="https://colab.research.google.com/github/prenio/MAT-421/blob/main/MAT_421_Module_D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MAT 421: Module D 1.1, 1.2, 1.3

## Section 1.1/1.2


Question: Let matrix A = [[1,2],[3,4],[5,6]] and B = [[6,5,4],[3,2,1]]. Compute the matrix product of A and B. Does this produce an error and why is this the case?

Import the necessary libararies.

In [21]:
import numpy as np
from numpy.linalg import eig
from numpy.linalg import qr

Use numpy to compute the product of the 2 matrices.

In [20]:
A,B = np.array([[1,2],[3,4],[5,6]]),np.array([[6,5,4],[3,2,1]])
print(A)
print(B, "\n")

product = np.dot(A,B)
print(product)

[[1 2]
 [3 4]
 [5 6]]
[[6 5 4]
 [3 2 1]] 

[[12  9  6]
 [30 23 16]
 [48 37 26]]


This does not produce an error because matrix A has the dimension (3,2) and the dimensions of matrix B is (2,3). These matrices are able to be multiplied together because the dimensions align.

The theory is that if matrix A has dimension (x,y) and matrix B has dimension (z,w), if y=z, then the matrix A can be multiplied to B (AB) without errors. If they were switched (BA), then the matrices can be multiplied if x=z. 
 

<br>Question: Let matrix A = [[1,2],[3,4],[5,6]] and B = [[6,5,4],[3,2,1]]. Calculate the eigenvalues and eigenvectors for these matrices using python.

In [19]:
A,B = np.array([[1,2],[3,4]]),np.array([[9,8,7],[6,5,4],[3,2,1]])

print("A: ",A)
evalue_a, evector_a = eig(A)
print("The eigenvalues of matrix A is: ", evalue_a)
print("The eigenvectors of matrix A is: ", evector_a, "\n")

print("B: ",B)
evalue_b, evector_b = eig(B)
print("The eigenvalues of matrix B is: ", evalue_b)
print("The eigenvectors of matrix B is: ", evector_b)

A:  [[1 2]
 [3 4]]
The eigenvalues of matrix A is:  [-0.37228132  5.37228132]
The eigenvectors of matrix A is:  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]] 

B:  [[9 8 7]
 [6 5 4]
 [3 2 1]]
The eigenvalues of matrix B is:  [ 1.61168440e+01 -1.11684397e+00 -5.03850873e-16]
The eigenvectors of matrix B is:  [[-0.8186735  -0.61232756  0.40824829]
 [-0.52532209  0.08675134 -0.81649658]
 [-0.23197069  0.78583024  0.40824829]]


## Section 1.3

Question: Let matrix A = [[4,3],[2,1]]. Use the qr function in python to find the eigenalues. Find the 1st, 5th, and 10th iterations. Compare this to the eigenvalue/eigenvector function.

In [31]:
A = np.array([[4, 3], 
              [2, 1]])

iter = [1,5,10]

for i in range(11):
  q,r = qr(A)
  A = np.dot(r,q)
  if i in iter:
    print("Iteration ",i,":")
    print(A,"\n")

evalue_a = eig(A)
print("The eigenvalues of matrix A is: ", evalue_a)

  

Iteration  1 :
[[ 5.36986301  1.01369863]
 [ 0.01369863 -0.36986301]] 

Iteration  5 :
[[ 5.37228127e+00  1.00000032e+00]
 [ 3.16147971e-07 -3.72281268e-01]] 

Iteration  10 :
[[ 5.37228132e+00 -1.00000000e+00]
 [ 5.05187875e-13 -3.72281323e-01]] 

The eigenvalues of matrix A is:  (array([ 5.37228132, -0.37228132]), array([[1.00000000e+00, 1.71498585e-01],
       [8.79419210e-14, 9.85184366e-01]]))


We can see that with more iterations, the eigenvalues get closer to the value found in the eigenvalue function.